#Clear overflow transfer
#Tue Feb 24 09:43:37 EST 2026
studyDurationSeconds=5400
sessions=4
balance=1000
breakDurationSeconds=300
studyHourlyRate=34.0
pendingOverflowAmount=0.0
breakDuration=5
pendingOverflowFromGoal=
studyDuration=10
currentGoalName=o
hourlyRate=20
