#User Settings
#Thu Feb 26 10:16:47 EST 2026
studyDurationSeconds=1500
sessions=2
pendingOverflowFromGoal=
currentGoalName=gpu
balance=1000
breakDurationSeconds=300
studyHourlyRate=34.0
pendingOverflowAmount=0.0
breakDuration=5
goal.link.gpu=https\://www.amazon.ca/GeForce-128-bit-Graphics-Control-ZT-A30500K-10M/dp/B0D4TV2PK2/ref\=dp_fod_d_sccl_1/140-2987167-4618236?pd_rd_w\=4Ni2f&content-id\=amzn1.sym.8785600f-2431-4bd9-b7e8-da352831dca4&pf_rd_p\=8785600f-2431-4bd9-b7e8-da352831dca4&pf_rd_r\=H2BR5X6WFANGSAWGN1GG&pd_rd_wg\=OKlpX&pd_rd_r\=91882791-4328-4a35-b680-40d207c3a4d4&pd_rd_i\=B0D4TV2PK2&psc\=1
studyDuration=10
hourlyRate=20
